#!/bin/bash
yay -S --noconfirm --needed aardvark-dns cockpit cockpit-packagekit cockpit-podman distrobox boxbuddy lxd netavark podman podman-docker
sudo systemctl enable --now lxd.service
sudo systemctl enable --now cockpit.socket
