#!/bin/bash
## Custom Scripts
sudo ln -sv $HOME/.dots/arch-scripts/bin/cliphist-rofi /usr/local/bin/cliphist-rofi
sudo ln -sv $HOME/.dots/arch-scripts/bin/hyprlauncher /usr/local/bin/hyprlauncher
sudo ln -sv $HOME/.dots/arch-scripts/bin/hyprrunner /usr/local/bin/hyprrunner
sudo ln -sv $HOME/.dots/arch-scripts/bin/hyprterm /usr/local/bin/hyprterm
sudo ln -sv $HOME/.dots/arch-scripts/bin/hyprtheme /usr/local/bin/hyprtheme
