#!/bin/bash
sudo systemctl set-default graphical.target
systemctl --user enable wireplumber.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service pipewire-pulse.socket pipewire.socket pipewire-pulse.service pipewire.service hypridle.service hyprpaper
sudo systemctl enable --now auditd apparmor jitterentropy sysstat haveged piavpn NetworkManager grub-btrfsd
sudo systemctl disable greetd
