#!/bin/bash
yay -S --noconfirm --needed caelestia-cli quickshell-git ddcutil brightnessctl app2unit cava networkmanager bluez-utils lm_sensors fish aubio libpipewire glibc qt6-declarative gcc-libs ttf-material-symbols-variable power-profiles-daemon ttf-jetbrains-mono-nerd grim swappy libqalculate
